# Generated by Django 5.2.17 on 2026-09-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_managed',
            field=models.BooleanField(default=True, help_text='Whether stock quantity is actively managed'),
        ),
        migrations.AddField(
            model_name='product',
            name='woocommerce_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Original WooCommerce product ID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
