# Generated by Django 6.1 on 2026-08-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('badge_text', models.CharField(blank=True, default='Featured Promotion', max_length=100)),
                ('button_text', models.CharField(default='Shop Now', max_length=100)),
                ('button_link', models.CharField(default='/shop/', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('bg_gradient', models.CharField(default='linear-gradient(135deg, #0d9488 0%, #065f46 100%)', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Orthobest Care Hub', max_length=200)),
                ('site_domain', models.CharField(default='orthobestcarehub.co.ke', max_length=200)),
                ('tagline', models.CharField(default="Kenya's Premier Destination for Orthopedic, Rehabilitation & Mobility Solutions", max_length=300)),
                ('phone_primary', models.CharField(default='+254 719 160 398', max_length=50)),
                ('phone_secondary', models.CharField(blank=True, default='+254 727 480 198', max_length=50)),
                ('whatsapp_number', models.CharField(default='254798246811', help_text='Number in international format without + or spaces (e.g. 254798246811)', max_length=50)),
                ('contact_email', models.EmailField(default='info@orthobestcarehub.co.ke', max_length=254)),
                ('physical_address', models.TextField(default='Mfangano Street, Travis Building, 3rd Floor, Room C37, Wing C (near Quickmart), Nairobi CBD, Kenya')),
                ('business_hours', models.CharField(default='Mon - Fri: 9:00 AM - 5:00 PM | Sat: 9:00 AM - 3:00 PM | Sun: Closed', max_length=255)),
                ('announcement_bar_enabled', models.BooleanField(default=True)),
                ('announcement_bar_text', models.CharField(default='🚚 Fast, Reliable Delivery Across Kenya | Free Consultations on Product Selection!', max_length=300)),
                ('announcement_bar_link', models.CharField(blank=True, default='/shop/', max_length=300)),
                ('currency_symbol', models.CharField(default='KSh', max_length=10)),
                ('currency_code', models.CharField(default='KES', max_length=10)),
                ('hero_headline', models.CharField(default='SUPPORT YOUR MOVEMENT. LIVE WITH CONFIDENCE.', max_length=255)),
                ('hero_subheadline', models.TextField(default='Premium orthopedic supports, rehabilitation devices, wheelchairs, and healthcare equipment curated to restore comfort, strength, and independence.')),
                ('hero_primary_cta_text', models.CharField(default='Shop Products', max_length=100)),
                ('hero_primary_cta_link', models.CharField(default='/shop/', max_length=200)),
                ('hero_secondary_cta_text', models.CharField(default='Talk to a Specialist', max_length=100)),
                ('hero_secondary_cta_link', models.CharField(default='/contact/', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('medical_disclaimer', models.TextField(default='Product information is provided for general informational purposes and does not replace professional medical diagnosis or advice. Always consult a licensed healthcare practitioner or physiotherapist when selecting specialized rehabilitation gear.')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=50000.0, help_text='Order amount above which standard delivery is free (if applicable)', max_digits=10)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('tiktok_url', models.URLField(blank=True, default='https://tiktok.com')),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('default_meta_title', models.CharField(default="Orthobest Care Hub | Kenya's Trusted Orthopedic & Rehabilitation Store", max_length=255)),
                ('default_meta_description', models.TextField(default='Buy premium wheelchairs, knee braces, cervical collars, walking aids, physiotherapy tools, and hospital beds in Nairobi, Kenya. Fast countrywide delivery.')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=255)),
                ('icon_svg', models.CharField(default='shield-check', help_text='Icon identifier (e.g. shield-check, truck, headset, badge-check)', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Badge',
                'verbose_name_plural': 'Trust Badges',
                'ordering': ['display_order'],
            },
        ),
    ]
