# Generated by Django 6.1 on 2026-09-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCarouselSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay', models.BooleanField(default=True, help_text='Enable automatic slide transitions')),
                ('autoplay_speed', models.PositiveIntegerField(default=5500, help_text='Time in milliseconds between slide transitions (e.g. 5000 = 5 seconds)')),
                ('show_arrows', models.BooleanField(default=True, help_text='Show navigation arrow controls when multiple slides exist')),
                ('show_indicators', models.BooleanField(default=True, help_text='Show slide dot indicators at the bottom')),
                ('pause_on_hover', models.BooleanField(default=True, help_text='Pause autoplay when hovering with mouse or touching on mobile')),
                ('transition_speed', models.PositiveIntegerField(default=600, help_text='Slide animation duration in milliseconds (e.g. 600)')),
                ('loop_slides', models.BooleanField(default=True, help_text='Loop back to the first slide after the last slide')),
            ],
            options={
                'verbose_name': 'Hero Carousel Settings',
                'verbose_name_plural': 'Hero Carousel Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal slide name for Django Admin management (e.g. Homepage Hero - Orthopedic Store)', max_length=200)),
                ('badge_text', models.CharField(default="KENYA'S #1 ORTHOPEDIC & REHAB STORE", help_text='Eyebrow / pill badge text displayed above the headline', max_length=120)),
                ('badge_icon', models.CharField(blank=True, default='✦', help_text='Icon or symbol prefix for the badge (e.g. ✦, ✨, 🩺)', max_length=50)),
                ('heading', models.TextField(default='SUPPORT YOUR MOVEMENT.\nLIVE WITH CONFIDENCE.', help_text='Main large hero heading. Line breaks entered here will be preserved on the frontend.')),
                ('description', models.TextField(default="Explore Kenya's highest quality orthopedic braces, rehabilitation equipment, manual & electric wheelchairs, and clinical homecare essentials.", help_text='Supporting paragraph / marketing message')),
                ('primary_button_text', models.CharField(blank=True, default='Shop Products →', help_text='Text for primary button (leave blank to hide)', max_length=100)),
                ('primary_button_url', models.CharField(blank=True, default='/shop/', help_text='Internal or external URL for primary button', max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, default='Talk to a Specialist', help_text='Text for secondary button (leave blank to hide)', max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, default='/contact/', help_text='Internal or external URL for secondary button', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Featured visual image for the right side of the hero', null=True, upload_to='hero_slides/')),
                ('image_alt_text', models.CharField(blank=True, default='Orthobest Care Hub Orthopedic & Rehabilitation Products Nairobi Kenya', help_text='Accessible description for screen readers and SEO', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the carousel (ascending order: 0, 1, 2...)')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display this slide on the live website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlideBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Trust/benefit message (e.g. Medical Graded, M-Pesa Friendly, Doorstep Delivery)', max_length=150)),
                ('icon', models.CharField(blank=True, default='✓', help_text='Symbol or checkmark prefix', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hero_slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='core.heroslide')),
            ],
            options={
                'verbose_name': 'Hero Slide Benefit',
                'verbose_name_plural': 'Hero Slide Benefits',
                'ordering': ['order'],
            },
        ),
    ]
