# Generated by Django 5.2.17 on 2026-09-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herocarouselsettings_heroslide_heroslidebenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/Orthobestcarehab'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/Orthobestcarehab'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://tiktok.com/@Orthobestcarehab'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://x.com/Orthobestcarehab'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://youtube.com/@Orthobestcarehab'),
        ),
    ]
