# Generated by Django 5.2.17 on 2026-09-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_announcement_bar_text_and_more'),
        ('core', '0003_alter_sitesettings_facebook_url_and_more'),
    ]

    operations = [
    ]
